services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: sigec
      POSTGRES_PASSWORD: sigec
      POSTGRES_DB: sigec_sm
    ports:
      - "5432:5432"
    volumes:
      - sigec_db_data:/var/lib/postgresql/data

volumes:
  sigec_db_data:
